### ISSUE TITLE
Unhandled error event when generating playlist

### ISSUE THREAD

**Issue by nthng** [tavvy/GPM-Playlister#15]
I was trying to generate a playlist from http://www.bbc.co.uk/music/playlists/zzzz4r but the script crashed with the following error and subsequently a playlist was not pushed to Google Play Music.

```

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 74.125.136.95:443
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

**Comment by tavvy** [comment]
Apologies for taking so long to look at this issue.
I just attempted to run the same command and it was successful.
Looks to me like a time out error when attempting to connect to the BBC site. Perhaps you could try running it again and let me know if its still an issue.
